//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace DAL
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class SampleDBEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“SampleDBEntities”部分中的连接字符串初始化新 SampleDBEntities 对象。
        /// </summary>
        public SampleDBEntities() : base("name=SampleDBEntities", "SampleDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SampleDBEntities 对象。
        /// </summary>
        public SampleDBEntities(string connectionString) : base(connectionString, "SampleDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 SampleDBEntities 对象。
        /// </summary>
        public SampleDBEntities(EntityConnection connection) : base(connection, "SampleDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<plus_file> plus_file
        {
            get
            {
                if ((_plus_file == null))
                {
                    _plus_file = base.CreateObjectSet<plus_file>("plus_file");
                }
                return _plus_file;
            }
        }
        private ObjectSet<plus_file> _plus_file;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_department> t_department
        {
            get
            {
                if ((_t_department == null))
                {
                    _t_department = base.CreateObjectSet<t_department>("t_department");
                }
                return _t_department;
            }
        }
        private ObjectSet<t_department> _t_department;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_educational> t_educational
        {
            get
            {
                if ((_t_educational == null))
                {
                    _t_educational = base.CreateObjectSet<t_educational>("t_educational");
                }
                return _t_educational;
            }
        }
        private ObjectSet<t_educational> _t_educational;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_employee> t_employee
        {
            get
            {
                if ((_t_employee == null))
                {
                    _t_employee = base.CreateObjectSet<t_employee>("t_employee");
                }
                return _t_employee;
            }
        }
        private ObjectSet<t_employee> _t_employee;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<t_position> t_position
        {
            get
            {
                if ((_t_position == null))
                {
                    _t_position = base.CreateObjectSet<t_position>("t_position");
                }
                return _t_position;
            }
        }
        private ObjectSet<t_position> _t_position;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 plus_file EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToplus_file(plus_file plus_file)
        {
            base.AddObject("plus_file", plus_file);
        }
    
        /// <summary>
        /// 用于向 t_department EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_department(t_department t_department)
        {
            base.AddObject("t_department", t_department);
        }
    
        /// <summary>
        /// 用于向 t_educational EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_educational(t_educational t_educational)
        {
            base.AddObject("t_educational", t_educational);
        }
    
        /// <summary>
        /// 用于向 t_employee EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_employee(t_employee t_employee)
        {
            base.AddObject("t_employee", t_employee);
        }
    
        /// <summary>
        /// 用于向 t_position EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddTot_position(t_position t_position)
        {
            base.AddObject("t_position", t_position);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleDBModel", Name="plus_file")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class plus_file : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 plus_file 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static plus_file Createplus_file(global::System.Int32 id)
        {
            plus_file plus_file = new plus_file();
            plus_file.id = id;
            return plus_file;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.String _type;
        partial void OntypeChanging(global::System.String value);
        partial void OntypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String size
        {
            get
            {
                return _size;
            }
            set
            {
                OnsizeChanging(value);
                ReportPropertyChanging("size");
                _size = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("size");
                OnsizeChanged();
            }
        }
        private global::System.String _size;
        partial void OnsizeChanging(global::System.String value);
        partial void OnsizeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String url
        {
            get
            {
                return _url;
            }
            set
            {
                OnurlChanging(value);
                ReportPropertyChanging("url");
                _url = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("url");
                OnurlChanged();
            }
        }
        private global::System.String _url;
        partial void OnurlChanging(global::System.String value);
        partial void OnurlChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pid
        {
            get
            {
                return _pid;
            }
            set
            {
                OnpidChanging(value);
                ReportPropertyChanging("pid");
                _pid = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pid");
                OnpidChanged();
            }
        }
        private global::System.String _pid;
        partial void OnpidChanging(global::System.String value);
        partial void OnpidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createdate
        {
            get
            {
                return _createdate;
            }
            set
            {
                OncreatedateChanging(value);
                ReportPropertyChanging("createdate");
                _createdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createdate");
                OncreatedateChanged();
            }
        }
        private Nullable<global::System.DateTime> _createdate;
        partial void OncreatedateChanging(Nullable<global::System.DateTime> value);
        partial void OncreatedateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> updatedate
        {
            get
            {
                return _updatedate;
            }
            set
            {
                OnupdatedateChanging(value);
                ReportPropertyChanging("updatedate");
                _updatedate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("updatedate");
                OnupdatedateChanged();
            }
        }
        private Nullable<global::System.DateTime> _updatedate;
        partial void OnupdatedateChanging(Nullable<global::System.DateTime> value);
        partial void OnupdatedateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> folder
        {
            get
            {
                return _folder;
            }
            set
            {
                OnfolderChanging(value);
                ReportPropertyChanging("folder");
                _folder = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("folder");
                OnfolderChanged();
            }
        }
        private Nullable<global::System.Int32> _folder;
        partial void OnfolderChanging(Nullable<global::System.Int32> value);
        partial void OnfolderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> num
        {
            get
            {
                return _num;
            }
            set
            {
                OnnumChanging(value);
                ReportPropertyChanging("num");
                _num = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("num");
                OnnumChanged();
            }
        }
        private Nullable<global::System.Int32> _num;
        partial void OnnumChanging(Nullable<global::System.Int32> value);
        partial void OnnumChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleDBModel", Name="t_department")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_department : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_department 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static t_department Createt_department(global::System.String id)
        {
            t_department t_department = new t_department();
            t_department.id = id;
            return t_department;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manager
        {
            get
            {
                return _manager;
            }
            set
            {
                OnmanagerChanging(value);
                ReportPropertyChanging("manager");
                _manager = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("manager");
                OnmanagerChanged();
            }
        }
        private global::System.String _manager;
        partial void OnmanagerChanging(global::System.String value);
        partial void OnmanagerChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String manager_name
        {
            get
            {
                return _manager_name;
            }
            set
            {
                Onmanager_nameChanging(value);
                ReportPropertyChanging("manager_name");
                _manager_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("manager_name");
                Onmanager_nameChanged();
            }
        }
        private global::System.String _manager_name;
        partial void Onmanager_nameChanging(global::System.String value);
        partial void Onmanager_nameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleDBModel", Name="t_educational")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_educational : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_educational 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static t_educational Createt_educational(global::System.String id)
        {
            t_educational t_educational = new t_educational();
            t_educational.id = id;
            return t_educational;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleDBModel", Name="t_employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_employee : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_employee 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static t_employee Createt_employee(global::System.String id)
        {
            t_employee t_employee = new t_employee();
            t_employee.id = id;
            return t_employee;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String loginname
        {
            get
            {
                return _loginname;
            }
            set
            {
                OnloginnameChanging(value);
                ReportPropertyChanging("loginname");
                _loginname = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("loginname");
                OnloginnameChanged();
            }
        }
        private global::System.String _loginname;
        partial void OnloginnameChanging(global::System.String value);
        partial void OnloginnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> age
        {
            get
            {
                return _age;
            }
            set
            {
                OnageChanging(value);
                ReportPropertyChanging("age");
                _age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("age");
                OnageChanged();
            }
        }
        private Nullable<global::System.Int32> _age;
        partial void OnageChanging(Nullable<global::System.Int32> value);
        partial void OnageChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> birthday
        {
            get
            {
                return _birthday;
            }
            set
            {
                OnbirthdayChanging(value);
                ReportPropertyChanging("birthday");
                _birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("birthday");
                OnbirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _birthday;
        partial void OnbirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnbirthdayChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dept_id
        {
            get
            {
                return _dept_id;
            }
            set
            {
                Ondept_idChanging(value);
                ReportPropertyChanging("dept_id");
                _dept_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dept_id");
                Ondept_idChanged();
            }
        }
        private global::System.String _dept_id;
        partial void Ondept_idChanging(global::System.String value);
        partial void Ondept_idChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String position
        {
            get
            {
                return _position;
            }
            set
            {
                OnpositionChanging(value);
                ReportPropertyChanging("position");
                _position = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("position");
                OnpositionChanged();
            }
        }
        private global::System.String _position;
        partial void OnpositionChanging(global::System.String value);
        partial void OnpositionChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private Nullable<global::System.Int32> _gender;
        partial void OngenderChanging(Nullable<global::System.Int32> value);
        partial void OngenderChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> married
        {
            get
            {
                return _married;
            }
            set
            {
                OnmarriedChanging(value);
                ReportPropertyChanging("married");
                _married = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("married");
                OnmarriedChanged();
            }
        }
        private Nullable<global::System.Int32> _married;
        partial void OnmarriedChanging(Nullable<global::System.Int32> value);
        partial void OnmarriedChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String salary
        {
            get
            {
                return _salary;
            }
            set
            {
                OnsalaryChanging(value);
                ReportPropertyChanging("salary");
                _salary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("salary");
                OnsalaryChanged();
            }
        }
        private global::System.String _salary;
        partial void OnsalaryChanging(global::System.String value);
        partial void OnsalaryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String educational
        {
            get
            {
                return _educational;
            }
            set
            {
                OneducationalChanging(value);
                ReportPropertyChanging("educational");
                _educational = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("educational");
                OneducationalChanged();
            }
        }
        private global::System.String _educational;
        partial void OneducationalChanging(global::System.String value);
        partial void OneducationalChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String country
        {
            get
            {
                return _country;
            }
            set
            {
                OncountryChanging(value);
                ReportPropertyChanging("country");
                _country = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("country");
                OncountryChanged();
            }
        }
        private global::System.String _country;
        partial void OncountryChanging(global::System.String value);
        partial void OncountryChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String city
        {
            get
            {
                return _city;
            }
            set
            {
                OncityChanging(value);
                ReportPropertyChanging("city");
                _city = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("city");
                OncityChanged();
            }
        }
        private global::System.String _city;
        partial void OncityChanging(global::System.String value);
        partial void OncityChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String remarks
        {
            get
            {
                return _remarks;
            }
            set
            {
                OnremarksChanging(value);
                ReportPropertyChanging("remarks");
                _remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("remarks");
                OnremarksChanged();
            }
        }
        private global::System.String _remarks;
        partial void OnremarksChanging(global::System.String value);
        partial void OnremarksChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String school
        {
            get
            {
                return _school;
            }
            set
            {
                OnschoolChanging(value);
                ReportPropertyChanging("school");
                _school = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("school");
                OnschoolChanged();
            }
        }
        private global::System.String _school;
        partial void OnschoolChanging(global::System.String value);
        partial void OnschoolChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> createtime
        {
            get
            {
                return _createtime;
            }
            set
            {
                OncreatetimeChanging(value);
                ReportPropertyChanging("createtime");
                _createtime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("createtime");
                OncreatetimeChanged();
            }
        }
        private Nullable<global::System.DateTime> _createtime;
        partial void OncreatetimeChanging(Nullable<global::System.DateTime> value);
        partial void OncreatetimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleDBModel", Name="t_position")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class t_position : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 t_position 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static t_position Createt_position(global::System.String id)
        {
            t_position t_position = new t_position();
            t_position.id = id;
            return t_position;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.String _id;
        partial void OnidChanging(global::System.String value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String dept_id
        {
            get
            {
                return _dept_id;
            }
            set
            {
                Ondept_idChanging(value);
                ReportPropertyChanging("dept_id");
                _dept_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("dept_id");
                Ondept_idChanged();
            }
        }
        private global::System.String _dept_id;
        partial void Ondept_idChanging(global::System.String value);
        partial void Ondept_idChanged();

        #endregion
    
    }

    #endregion
    
}
